[features]
seeds = false
skip-lint = false

[programs.localnet]
squircl_did = "EaZScR64cJVXacumi8M4bb72385F9cXWu6ToutedHBXU"

[programs.devnet]
squircl_did = "EaZScR64cJVXacumi8M4bb72385F9cXWu6ToutedHBXU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "/Users/anish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test_identiy = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/squircl_identity.ts"
test_did = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/squircl_did.ts"
